# Generated by Django 5.2.8 on 2026-04-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='doe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('dropoff_time', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_status', models.CharField(blank=True, max_length=50, null=True)),
                ('authorized_guardian', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.child')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('behavior_type', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to='core.child')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.JSONField(default=dict)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_record', to='core.child')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.BooleanField(default=False)),
                ('snack1', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('snack2', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_records', to='core.child')),
            ],
        ),
    ]
