# Generated by Django 5.2.8 on 2026-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_child_address_child_allergies_child_dob_child_doe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
