# Generated by Django 5.2.8 on 2026-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_child_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='guardian_name',
            new_name='father_name',
        ),
        migrations.AddField(
            model_name='child',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
