# Generated by Django 5.2.8 on 2026-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_child_other_guardian_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='core.userprofile'),
        ),
    ]
