# Generated by Django 5.2.8 on 2026-05-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_child_parent_child_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='address',
        ),
        migrations.RemoveField(
            model_name='child',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='other_guardian_name',
        ),
        migrations.RemoveField(
            model_name='nutritionrecord',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='nutritionrecord',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='nutritionrecord',
            name='snack1',
        ),
        migrations.RemoveField(
            model_name='nutritionrecord',
            name='snack2',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='absence_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='enrollment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='father_middle_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_middle_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='other_guardian_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='other_guardian_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='other_guardian_middle_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='purok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionrecord',
            name='snack_status',
            field=models.CharField(blank=True, choices=[('Naubos', 'Naubos'), ('May tira', 'May tira'), ('Hindi naubos', 'Hindi naubos')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.schoolyear'),
        ),
        migrations.AddField(
            model_name='child',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_children', to='core.schoolyear'),
        ),
        migrations.AddField(
            model_name='nutritionrecord',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_records', to='core.schoolyear'),
        ),
        migrations.DeleteModel(
            name='BehaviorRecord',
        ),
    ]
