# Generated by Django 5.2.8 on 2026-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionrecord',
            name='teacher_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
