# Generated by Django 5.2.8 on 2026-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_engagementrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='parent_profiles/'),
        ),
        migrations.AlterField(
            model_name='child',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='child_profiles/'),
        ),
    ]
