# Generated by Django 5.2.8 on 2026-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_profile_pic_alter_child_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionrecord',
            name='snack_status',
            field=models.CharField(blank=True, choices=[('Finished', 'Finished'), ('Some Left', 'Some Left'), ('Not Eaten', 'Not Eaten')], max_length=50, null=True),
        ),
    ]
