# Generated by Django 5.2.8 on 2026-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_noclassday'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='health_conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
