# Generated by Django 5.2.8 on 2026-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_child_gender_child_health_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
