# Generated by Django 5.2.8 on 2026-05-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_child_height_child_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECCDDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='fa-star', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ECCDAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_period', models.CharField(choices=[('1st', '1st Assessment'), ('2nd', '2nd Assessment'), ('3rd', '3rd Assessment')], max_length=10)),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('concerns', models.TextField(blank=True, null=True)),
                ('follow_up_action', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eccd_assessments', to='core.child')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eccd_assessments', to='core.schoolyear')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ECCDMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.CharField(max_length=500)),
                ('age_bracket_min_months', models.IntegerField(default=0)),
                ('age_bracket_max_months', models.IntegerField(default=72)),
                ('order_number', models.IntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.eccddomain')),
            ],
        ),
        migrations.CreateModel(
            name='ECCDMilestoneScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_score', models.IntegerField(blank=True, choices=[(0, 'Not Yet Observed'), (1, 'Emerging'), (2, 'Consistently Demonstrated')], null=True)),
                ('parent_score', models.IntegerField(blank=True, choices=[(0, 'Not Yet Observed'), (1, 'Emerging'), (2, 'Consistently Demonstrated')], null=True)),
                ('teacher_observation', models.TextField(blank=True, null=True)),
                ('parent_observation', models.TextField(blank=True, null=True)),
                ('date_checked', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.eccdassessment')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eccdmilestone')),
            ],
            options={
                'unique_together': {('assessment', 'milestone')},
            },
        ),
    ]
