# Generated by Django 5.2.8 on 2026-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_eccddomain_eccdassessment_eccdmilestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eccdmilestone',
            name='material_procedure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
