# Generated by Django 6.0.4 on 2026-05-25 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_eccdmilestone_material_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eccdassessment',
            name='assessment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
