# Generated by Django 6.0.4 on 2026-06-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_scoringaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='eccd_1st_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='eccd_1st_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='eccd_2nd_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='eccd_2nd_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='eccd_3rd_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='eccd_3rd_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.activity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_completions', to='core.child')),
            ],
            options={
                'unique_together': {('child', 'activity')},
            },
        ),
    ]
