# Generated by Django 5.2.8 on 2026-06-07 05:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_schoolyear_eccd_1st_end_schoolyear_eccd_1st_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1st', '1st Quarter'), ('2nd', '2nd Quarter'), ('3rd', '3rd Quarter')], max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('measurement_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi_records', to='core.child')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bmi_records', to='core.schoolyear')),
            ],
            options={
                'unique_together': {('child', 'school_year', 'quarter')},
            },
        ),
    ]
