# Generated by Django 6.0.4 on 2026-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bmirecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
