# Generated by Django 5.2.8 on 2026-08-22 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_schoolyear_deleted_at_schoolyear_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_highlights/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='General Reminder', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Enrollment', 'Enrollment'), ('Important Notice', 'Important Notice'), ('Schedule', 'Schedule'), ('Daycare Suspension', 'Daycare Suspension'), ('Parent Reminder', 'Parent Reminder'), ('Activities', 'Activities'), ('Events', 'Events'), ('Health & Safety', 'Health & Safety'), ('Program Highlights', 'Program Highlights')], default='General', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Scheduled', 'Scheduled'), ('Expired', 'Expired'), ('Archived', 'Archived')], default='Published', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='Child Development Program', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('age_requirement', models.CharField(default='3 to 4.11 years old', max_length=100)),
                ('available_slots', models.IntegerField(default=30)),
                ('requirements_text', models.TextField(blank=True, default='• Photocopy of PSA Birth Certificate\n• 2x2 ID Photo of Child (2 copies)\n• Barangay Certificate of Residency\n• Parent/Guardian Government Issued ID\n• Child Health / Immunization Record', null=True)),
                ('instructions_text', models.TextField(blank=True, default='Please visit the Barangay Market View 3 Child Development Center to submit requirements or contact center administration for enrollment details.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_info', to='core.schoolyear')),
            ],
        ),
    ]
