# Generated by Django 5.2.8 on 2026-08-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_programhighlight_publicreminder_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_address_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
