# Generated by Django 5.2.8 on 2026-08-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userprofile_home_address_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(default='Barangay Market View 3 Child Development Center', max_length=150)),
                ('short_name', models.CharField(default='BMV3', max_length=50)),
                ('system_title', models.CharField(default='Child Care Management System', max_length=150)),
                ('tagline', models.CharField(default='Nurturing Early Childhood Development', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='center_branding/')),
                ('center_latitude', models.DecimalField(decimal_places=7, default=13.938, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, default=121.6146, max_digits=10)),
                ('address_text', models.TextField(default='Barangay Market View 3, Lucena City')),
                ('contact_phone', models.CharField(blank=True, default='(042) 710-1234', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='center@bmv3.edu.ph', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
