# Generated by Django 5.2.8 on 2026-08-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_centersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextblastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(default='General Announcement', max_length=50)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=True)),
                ('target_group', models.CharField(default='All Active Parents', max_length=100)),
                ('emails_sent_count', models.IntegerField(default=0)),
                ('sms_sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
        ),
    ]
